### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by EvgenyOrekhov** [nikoskalogridis/jslint-node#3]
JSLint edition `"2018-10-22"` doesn't work anymore:

```text
> jslint-node@1.2.5 postinstall /home/user/example/node_modules/jslint-node
> node bin/jslint.js --update

Downloading JSLint from github...
evalmachine.<anonymous>:4854
export default Object.freeze(function jslint(
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at compileJSLint (/home/user/example/node_modules/jslint-node/lib/index.js:18:22)
    at /home/user/example/node_modules/jslint-node/lib/index.js:44:26
    at tryCatchReject (/home/user/example/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/home/user/example/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/home/user/example/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/home/user/example/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/home/user/example/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/home/user/example/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by nikoskalogridis** [comment]
Thanks, please try now

**Comment by EvgenyOrekhov** [comment]
@nikoskalogridis It works now, thanks!
